// registry.js — รายชื่อเกมทั้งหมด
// แต่ละเกม: { id, name, emoji, module }
//   module = path (relative จาก js/app.js) ของ ES module ที่ export mount(root, game) / unmount()
// เพิ่มเกมใหม่ = เพิ่ม 1 object + สร้างไฟล์ js/games/<id>.js
export const GAMES = [
  { id: 'kingscup',    name: 'Kings Cup',  emoji: '🃏', module: './games/kingscup.js' },
  { id: 'truthordare', name: 'จริง/กล้า',  emoji: '😈', module: './games/truthordare.js' },
  { id: 'mostlikely',  name: 'ใครน่าจะ',   emoji: '👉', module: './games/mostlikely.js' },
  { id: 'wheel',       name: 'วงล้อ',      emoji: '🎡', module: './games/wheel.js' },
  { id: 'picker',      name: 'สุ่มคน',      emoji: '🎯', module: './games/picker.js' },
  { id: 'pairing',     name: 'จับคู่',      emoji: '💞', module: './games/pairing.js' },
  { id: 'charades',    name: 'ใบ้คำ',       emoji: '🎭', module: './games/charades.js' },
  { id: 'crocodile',   name: 'ฟันจรเข้',    emoji: '🐊', module: './games/crocodile.js' },
  { id: 'dice',        name: 'ลูกเต๋า',     emoji: '🎲', module: './games/dice.js' },
  { id: 'race',        name: 'วิ่งแข่ง',    emoji: '🏁', module: './games/race.js' },
  { id: 'bomb',        name: 'ระเบิดเวลา',  emoji: '💣', module: './games/bomb.js' },
  { id: 'neverever',   name: 'ฉันไม่เคย',   emoji: '🙅', module: './games/neverever.js' },
  { id: 'reaction',    name: 'ปฏิกิริยา',   emoji: '⚡', module: './games/reaction.js' },
  { id: 'balloon',     name: 'ลูกโป่ง',     emoji: '🎈', module: './games/balloon.js' },
  { id: 'liedetector', name: 'จับโกหก',     emoji: '🔍', module: './games/liedetector.js' },
  { id: 'challenge7',  name: 'ท้า 7 วิ',    emoji: '⏱️', module: './games/challenge7.js' },
  { id: 'memory',      name: 'จับคู่จำ',    emoji: '🧠', module: './games/memory.js' },
  { id: 'whack',       name: 'ตบตัวตุ่น',   emoji: '🐹', module: './games/whack.js' },
  { id: 'highlow',     name: 'สูงต่ำ',      emoji: '🔢', module: './games/highlow.js' },
  { id: 'stopbar',     name: 'หยุดตรง',     emoji: '🎯', module: './games/stopbar.js' },
  { id: 'rps',         name: 'เป่ายิงฉุบ',  emoji: '✊', module: './games/rps.js' },
  { id: 'stroop',      name: 'จับผิดสี',    emoji: '🎨', module: './games/stroop.js' },
  { id: 'simon',       name: 'ทำตามลำดับ',  emoji: '🔴', module: './games/simon.js' },
  { id: 'coin',        name: 'หัวก้อย',     emoji: '🪙', module: './games/coin.js' },
  { id: 'trivia',      name: 'ควิซ',        emoji: '❓', module: './games/trivia.js' },
  { id: 'emojiquiz',   name: 'ทายอิโมจิ',   emoji: '🎬', module: './games/emojiquiz.js' },
  { id: 'wyr',         name: 'เลือกสิ',     emoji: '🤔', module: './games/wouldyourather.js' },
  { id: 'mathsprint',  name: 'เลขเร็ว',     emoji: '🧮', module: './games/mathsprint.js' },
  { id: 'fortune',     name: 'ดวงวันนี้',   emoji: '🔮', module: './games/fortune.js' },
  { id: 'tapduel',     name: 'ตบมือดวล',    emoji: '🥊', module: './games/tapduel.js' },
];
