// registry.js — รายชื่อเกมทั้งหมด
// แต่ละเกม: { id, name, emoji, module }
//   module = path (relative จาก js/app.js) ของ ES module ที่ export mount(root, game) / unmount()
// เพิ่มเกมใหม่ = เพิ่ม 1 object + สร้างไฟล์ js/games/<id>.js
export const GAMES = [
  { id: 'kingscup',    name: 'Kings Cup',  emoji: '🃏', module: './games/kingscup.js' },
  { id: 'truthordare', name: 'จริง/กล้า',  emoji: '😈', module: './games/truthordare.js' },
  { id: 'mostlikely',  name: 'ใครน่าจะ',   emoji: '👉', module: './games/mostlikely.js' },
  { id: 'wheel',       name: 'วงล้อ',      emoji: '🎡', module: './games/wheel.js' },
  { id: 'picker',      name: 'สุ่มคน',      emoji: '🎯', module: './games/picker.js' },
  { id: 'pairing',     name: 'จับคู่',      emoji: '💞', module: './games/pairing.js' },
  { id: 'charades',    name: 'ใบ้คำ',       emoji: '🎭', module: './games/charades.js' },
  { id: 'crocodile',   name: 'ฟันจรเข้',    emoji: '🐊', module: './games/crocodile.js' },
  { id: 'corgi',       name: 'คอร์กี้',     emoji: '🐶', module: './games/corgi.js' },
  { id: 'dice',        name: 'ลูกเต๋า',     emoji: '🎲', module: './games/dice.js' },
  { id: 'race',        name: 'วิ่งแข่ง',    emoji: '🏁', module: './games/race.js' },
  { id: 'bomb',        name: 'ระเบิดเวลา',  emoji: '💣', module: './games/bomb.js' },
  { id: 'neverever',   name: 'ฉันไม่เคย',   emoji: '🙅', module: './games/neverever.js' },
  { id: 'reaction',    name: 'ปฏิกิริยา',   emoji: '⚡', module: './games/reaction.js' },
  { id: 'balloon',     name: 'ลูกโป่ง',     emoji: '🎈', module: './games/balloon.js' },
  { id: 'liedetector', name: 'จับโกหก',     emoji: '🔍', module: './games/liedetector.js' },
  { id: 'challenge7',  name: 'ท้า 7 วิ',    emoji: '⏱️', module: './games/challenge7.js' },
  { id: 'memory',      name: 'จับคู่จำ',    emoji: '🧠', module: './games/memory.js' },
  { id: 'whack',       name: 'ตบตัวตุ่น',   emoji: '🐹', module: './games/whack.js' },
  { id: 'highlow',     name: 'สูงต่ำ',      emoji: '🔢', module: './games/highlow.js' },
  { id: 'stopbar',     name: 'หยุดตรง',     emoji: '🎯', module: './games/stopbar.js' },
  { id: 'rps',         name: 'เป่ายิงฉุบ',  emoji: '✊', module: './games/rps.js' },
  { id: 'stroop',      name: 'จับผิดสี',    emoji: '🎨', module: './games/stroop.js' },
  { id: 'simon',       name: 'ทำตามลำดับ',  emoji: '🔴', module: './games/simon.js' },
  { id: 'coin',        name: 'หัวก้อย',     emoji: '🪙', module: './games/coin.js' },
  { id: 'trivia',      name: 'ควิซ',        emoji: '❓', module: './games/trivia.js' },
  { id: 'emojiquiz',   name: 'ทายอิโมจิ',   emoji: '🎬', module: './games/emojiquiz.js' },
  { id: 'wyr',         name: 'เลือกสิ',     emoji: '🤔', module: './games/wouldyourather.js' },
  { id: 'mathsprint',  name: 'เลขเร็ว',     emoji: '🧮', module: './games/mathsprint.js' },
  { id: 'fortune',     name: 'ดวงวันนี้',   emoji: '🔮', module: './games/fortune.js' },
  { id: 'tapduel',     name: 'ตบมือดวล',    emoji: '🥊', module: './games/tapduel.js' },
  { id: 'tapsprint',   name: 'รัวปุ่ม',     emoji: '👆', module: './games/tapsprint.js' },
  { id: 'targetaim',   name: 'ยิงเป้า',     emoji: '🏹', module: './games/targetaim.js' },
  { id: 'numberrush',  name: 'เรียงเลข',    emoji: '🔟', module: './games/numberrush.js' },
  { id: 'arrowtap',    name: 'ปัดทิศ',      emoji: '⬆️', module: './games/arrowtap.js' },
  { id: 'oddoneout',   name: 'หาตัวต่าง',   emoji: '🔍', module: './games/oddoneout.js' },
  { id: 'timeguess',   name: 'ทายเวลา',     emoji: '⏲️', module: './games/timeguess.js' },
  { id: 'tfmath',      name: 'ถูก/ผิด',     emoji: '➗', module: './games/tfmath.js' },
  { id: 'countit',     name: 'นับให้ไว',    emoji: '👀', module: './games/countit.js' },
  { id: 'taboo',       name: 'คำต้องห้าม',  emoji: '🚫', module: './games/taboo.js' },
  { id: 'tongue',      name: 'ลิ้นพันกัน',  emoji: '👅', module: './games/tongue.js' },
  { id: 'category',    name: 'หมวด ก-ฮ',    emoji: '🔤', module: './games/category.js' },
  { id: 'impostor',    name: 'ใครนอกคอก',   emoji: '🕵️', module: './games/impostor.js' },
  { id: 'magic8',      name: 'ลูกแก้ว',     emoji: '🎱', module: './games/magic8.js' },
  { id: 'lovemeter',   name: 'วัดรัก',      emoji: '❤️', module: './games/lovemeter.js' },
  { id: 'teamsplit',   name: 'แบ่งทีม',     emoji: '👥', module: './games/teamsplit.js' },
  { id: 'turnorder',   name: 'ลำดับเล่น',   emoji: '🔀', module: './games/turnorder.js' },
  { id: 'slot',        name: 'สล็อต',       emoji: '🎰', module: './games/slot.js' },
  { id: 'punishment',  name: 'บทลงโทษ',     emoji: '🎁', module: './games/punishment.js' },
  { id: 'scratch',     name: 'ขูดดวง',      emoji: '🍀', module: './games/scratch.js' },
  { id: 'actiondice',  name: 'เต๋าคำสั่ง',  emoji: '🀄', module: './games/actiondice.js' },
  { id: 'breakout',    name: 'ทุบบล็อก',    emoji: '🧱', module: './games/breakout.js' },
  { id: 'snake',       name: 'งูงับ',       emoji: '🐍', module: './games/snake.js' },
  { id: 'pong',        name: 'ปิงปองคู่',   emoji: '🏓', module: './games/pong.js' },
  { id: 'slide',       name: 'ปริศนาเลื่อน', emoji: '🧩', module: './games/slide.js' },
  { id: 'wordguess',   name: 'ทายคำไทย',    emoji: '📝', module: './games/wordguess.js' },
];
